### ISSUE TITLE
Disconnecting generates an error in the Django process

### ISSUE THREAD

**Issue by samuell** [neicnordic/sftpbeamer#4]
When clicking the disconnect, the following traceback is shown in the frontend process:

```python
Internal Server Error: /sftp_beamer/dashboard/disconnect
Traceback (most recent call last):
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/samuel/code/bils/sftpproxy.github/sftp_beamer/sftp_beamer/utils.py", line 10, in func_wrapper
    return func(self, request)
  File "/home/samuel/code/bils/sftpproxy.github/sftp_beamer/sftp_beamer/views.py", line 98, in get
    ZmqMessageKeys.SESSION_KEY: session_key})
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/site-packages/zmq/sugar/socket.py", line 388, in send_json
    msg = jsonapi.dumps(obj, **kwargs)
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/site-packages/zmq/utils/jsonapi.py", line 55, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/samuel/.pyenv/versions/3.4.3/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
[20/Nov/2015 18:23:55]"GET /sftp_beamer/dashboard/disconnect?source=host1 HTTP/1.1" 500 15470
```

**Comment by samuell** [comment]
Fixed in 7720230947415eeb8a6433d47b2544c6c801b30f
